version: '3.9'

services:
  auth_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: authdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - '5433:5432'
    # volumes:
      # - my-postgres:/var/lib/postgresql/data

  backend_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: backenddb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - '5433:5432'
    # volumes:
    #   - my-postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    # environment:
    #   REDIS_HOST: localhost
    # volumes:
    #   - my-redis:/data
    ports:
      - '6379:6379'

  auth:
    build: ./auth-service
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_NAME: authdb
      DB_USER: mydb
      DB_PASSWORD: mypassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: mysecret
    ports:
      - '5000:4000'
    depends_on:
      - auth_db
      - redis

  backend:
    build: ./finalEvalBE
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: backend_db
      DB_PORT: 5432
      DB_NAME: backenddb
      DB_USER: mydb
      DB_PASSWORD: mypassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8080:8080'
    depends_on:
      - backend_db
  auth_migration:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.migration
      args:
        - no_cache=1
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      DB_USER: mydb
      DB_PASSWORD: mypassword
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_NAME: authdb

  backend_migration:
    build:
      context: ./finalEvalBE
      dockerfile: Dockerfile.migration
      args:
        - no_cache=1
    depends_on:
      backend_db:
        condition: service_healthy
    environment:
      DB_USER: mydb
      DB_PASSWORD: mypassword
      DB_HOST: backend_db
      DB_PORT: 5432
      DB_NAME: backenddb
volumes:
  my-postgres:
  my-redis:
